[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  external_node_modules = ["@netlify/functions"]
  included_files = ["src/app/api/**/*"]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/zoho-domain-verification.html"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-cache"
    X-Frame-Options = "ALLOW"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://synvra.com;"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000

[context.production.environment]
  SMTP_HOST = "smtp.gmail.com"
  SMTP_PORT = "587"
  SMTP_SECURE = "false"
  SMTP_FROM = "noreply@synvra.com"
  QUOTE_EMAIL = "quotes@synvra.com"
  NEXT_PUBLIC_API_URL = "https://api.synvra.com" 