# This is the recommended configuration for a Next.js 14 site on Netlify.
# It relies on the official Next.js plugin to handle all routing and configuration automatically.

[build]
  # The build command for Next.js
  command = "npm run build"
  
  # The directory where Next.js outputs the build files
  publish = ".next"
  # The functions directory is automatically set by the Next.js plugin
  # functions = "netlify/functions" 

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  # These are now handled automatically by the Next.js plugin
  # external_node_modules = ["@node-rs/bcrypt", "stripe"]
  # included_files = ["src/app/api/**/*"]
  # node_bundler = "esbuild"

# This plugin is essential for Next.js sites on Netlify.
# It automatically configures redirects, serverless functions, and more.
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/zoho-domain-verification.html"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-cache"
    X-Frame-Options = "ALLOW"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com https://static.zdassets.com https://*.zendesk.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.synvra.com https://www.google-analytics.com https://ekr.zdassets.com https://*.zendesk.com https://synvra.zendesk.com; frame-src 'self' https://tawk.to https://*.zendesk.com;"

# This catch-all redirect is for SPAs and conflicts with Next.js routing.
# The @netlify/plugin-nextjs handles this automatically.
# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

[dev]
  framework = "next"
  targetPort = 3000

[context.production.environment]
  SMTP_HOST = "smtp.gmail.com"
  SMTP_PORT = "587"
  SMTP_SECURE = "false"
  SMTP_FROM = "noreply@synvra.com"
  QUOTE_EMAIL = "quotes@synvra.com"
  NEXT_PUBLIC_API_URL = "https://api.synvra.com" 