[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://synvra.com"
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "www.synvra.com/*"
  to = "https://synvra.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 