[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_DOMAIN = "synvra.com"
  NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-CD8S6EHSRZ"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
