[build]
  command = "npm run build"
  publish = ".next"
  base = "frontend"

[context.production]
  command = "npm run build"

[context.development]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://dev.synvra.com"
  NODE_VERSION = "18" 