[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NEXT_STATIC_BUILD = "true"
  NODE_VERSION = "18.20.8"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
