[build]
  base = "."
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_DOMAIN = "synvra.com"
  NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-CD8S6EHSRZ"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "http://synvra.com/*"
  to = "https://synvra.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.synvra.com/*"
  to = "https://synvra.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.synvra.com/*"
  to = "https://synvra.com/:splat"
  status = 301
  force = true
