[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[context.production]
  command = "npm install && npm run build"

[context.development]
  command = "npm install && npm run build"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://synvra.com"
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@node-rs/*"]
  included_files = ["next.config.js"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "www.synvra.com/*"
  to = "https://synvra.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true 