[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_DOMAIN = "synvra.com"
  NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-CD8S6EHSRZ"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"
  NEXT_STATIC_BUILD = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/en/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/de/*"
  to = "/de/index.html"
  status = 200

[[redirects]]
  from = "/ja/*"
  to = "/ja/index.html"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/zh/index.html"
  status = 200
