# This is the recommended configuration for a Next.js 14 site on Netlify.
# It relies on the official Next.js plugin to handle all routing and configuration automatically.

[build]
  # The build command for Next.js
  command = "npm run build"
  
  # The directory where Next.js outputs the build files
  publish = ".next"
  # The functions directory is automatically set by the Next.js plugin
  # functions = "netlify/functions" 

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  # These are now handled automatically by the Next.js plugin
  # external_node_modules = ["@node-rs/bcrypt", "stripe"]
  # included_files = ["src/app/api/**/*"]
  # node_bundler = "esbuild"

# This plugin is essential for Next.js sites on Netlify.
# It automatically configures redirects, serverless functions, and more.
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://static.zdassets.com https://ekr.zdassets.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://region1.google-analytics.com https://stats.g.doubleclick.net wss://widget-mediator.zopim.com https://*.zendesk.com https://*.zdassets.com;
      frame-src https://widget.zendesk.com https://widget-mediator.zopim.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://checkout.stripe.com;
    """

# This catch-all redirect is for SPAs and conflicts with Next.js routing.
# The @netlify/plugin-nextjs handles this automatically.
# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

[dev]
  framework = "next"
  targetPort = 3000

[context.production.environment]
  SMTP_HOST = "smtp.gmail.com"
  SMTP_PORT = "587"
  SMTP_SECURE = "false"
  SMTP_FROM = "noreply@synvra.com"
  QUOTE_EMAIL = "quotes@synvra.com"
  NEXT_PUBLIC_API_URL = "https://api.synvra.com" 