[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/.netlify/functions/api"
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  directory = "netlify/functions"
  included_files = ["src/app/api/**/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API requests through Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Content-Type = "application/json"

# Ensure static files are served first
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Handle analytics API
[[redirects]]
  from = "/.netlify/functions/analytics/*"
  to = "/.netlify/functions/analytics/:splat"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/zoho-domain-verification.html"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-cache"
    X-Frame-Options = "ALLOW"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: https://www.google-analytics.com; font-src 'self' data:; connect-src 'self' https://synvra.com https://www.google-analytics.com /.netlify/functions/*;"
    X-Robots-Tag = "index, follow"

# Handle dynamic routes
[[redirects]]
  from = "/services/*"
  to = "/services/[slug]"
  status = 200

[[redirects]]
  from = "/portfolio/*"
  to = "/portfolio/[slug]"
  status = 200

[[redirects]]
  from = "/work"
  to = "/portfolio"
  status = 301
  force = true

# Final catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 