[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://synvra.com"
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 